export function normalize(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

export const PROPERTY_TYPE_SYNONYMS: Record<string, string[]> = {
  habitaciones: [
    "habitacion",
    "habitaciones",
    "cuarto",
    "cuartos",
    "pieza",
    "piezas",
    "alcoba",
    "alcobas",
  ],
  apartaestudios: [
    "apartaestudio",
    "apartaestudios",
    "aparta estudio",
    "aparta-estudio",
    "aparta estudios",
    "aparta-estudios",
  ],
  apartamentos: [
    "apartamento",
    "apartamentos",
    "apto",
    "aptos",
    "apto.",
  ],
};

export const LOCATION_SYNONYMS: Record<string, string[]> = {
  "centro de medellin": [
    "centro de medellin",
    "centro de medellín",
    "centro medellin",
    "centro medellín",
    "av la playa",
    "la playa",
    "parque berrio",
    "parque berrío",
    "san antonio",
    "la candelaria",
    "junin",
    "junín",
    "maracaibo",
    "el hueco",
  ],
  "el poblado": [
    "el poblado",
    "poblado",
    "milla de oro",
    "ciudad del rio",
    "ciudad del río",
    "provenza",
    "lleras",
  ],
  laureles: [
    "laureles",
    "la 70",
    "carrera 70",
    "estadio",
    "la setenta",
    "segundo parque de laureles",
    "primer parque de laureles",
    "circular",
  ],
  belen: [
    "belen",
    "belén",
    "la mota",
    "los molinos",
    "fatima",
    "fátima",
    "belen malibu",
    "belén malibú",
  ],
  envigado: ["envigado", "la frontera", "zuniga", "zúñiga"],
  sabaneta: ["sabaneta"],
  itagui: ["itagui", "itagüí", "ditaires"],
  bello: ["bello", "niquia", "niquía"],
  boston: ["boston"],
  "buenos aires": ["buenos aires"],
  bombona: ["bombona", "bomboná"],
  "san joaquin": ["san joaquin", "san joaquín"],
  robledo: ["robledo", "palenque"],
  aranjuez: ["aranjuez", "manrique", "campo valdes", "campo valdés"],
  "la america": [
    "la america",
    "la américa",
    "simon bolivar",
    "simón bolívar",
  ],
  calasanz: ["calasanz", "la floresta", "santa lucia", "santa lucía"],
  castilla: ["castilla", "caribe", "tricentenario"],
  prado: ["prado", "hospital", "chagualo"],
  copacabana: ["copacabana"],
  barbosa: ["barbosa"],
  girardota: ["girardota"],
  caldas: ["caldas"],
  "la estrella": ["la estrella"],
  "carlos e. restrepo": ["carlos e. restrepo", "carlos e restrepo", "suramericana"],
  "universidad de antioquia": [
    "universidad de antioquia",
    "udea",
    "u de a",
    "u. de a.",
    "alma mater",
  ],
  "universidad pontificia bolivariana": [
    "universidad pontificia bolivariana",
    "upb",
    "pontificia",
    "bolivariana",
  ],
  "universidad nacional": [
    "universidad nacional",
    "unal",
    "u nacional",
    "u. nacional",
    "minas",
  ],
  "universidad de medellin": [
    "universidad de medellin",
    "universidad de medellín",
    "udem",
  ],
  eafit: ["eafit", "universidad eafit"],
  itm: ["itm", "instituto tecnologico metropolitano"],
  "estacion hospital": ["estacion hospital", "hospital"],
  "estacion universidad": ["estacion universidad"],
  "estacion suramericana": ["estacion suramericana", "suramericana"],
  "estacion estadio": ["estacion estadio"],
  "estacion poblado": ["estacion poblado"],
  "estacion aguacatala": ["estacion aguacatala", "aguacatala"],
  "estacion envigado": ["estacion envigado"],
  "estacion itagui": ["estacion itagui"],
  "estacion sabaneta": ["estacion sabaneta"],
  "estacion niquia": ["estacion niquia"],
  "estacion caribe": ["estacion caribe"],
  "estacion gardel": ["estacion gardel", "gardel"],
};

export const AMENITY_SYNONYMS: Record<string, string[]> = {
  banoPrivado: [
    "bano privado",
    "baño privado",
    "bano interno",
    "baño interno",
    "bano propio",
    "baño propio",
    "bano independiente",
    "baño independiente",
    "bano dentro",
    "baño dentro",
    "bano en la habitacion",
    "baño en la habitación",
    "bano en el cuarto",
    "baño en el cuarto",
  ],
  bano: ["bano", "baño"],
  lavanderia: [
    "lavanderia",
    "lavandería",
    "lavadora",
    "servicio de lavanderia",
    "servicio de lavandería",
    "zona de lavado",
    "zona de ropas",
  ],
  serviciosPublicos: [
    "servicios incluidos",
    "servicios publicos",
    "servicios públicos",
    "todos los servicios",
    "todo incluido",
  ],
};

export const SEEKING_PATTERNS: RegExp[] = [
  /\bbusco\b/i,
  /\bnecesito\b/i,
  /\bse\s+busca\b/i,
  /\bbuscando\b/i,
  /\bme\s+interesa\b/i,
  /\balguien\s+(que\s+)?arriende\b/i,
  /\brecomendaci[oó]n\b/i,
];

export const PRICE_CONTEXT_WORDS = [
  "precio",
  "valor",
  "mensual",
  "mes",
  "arriendo",
  "alquiler",
  "canon",
  "\\$",
  "pesos",
  "incluidos",
  "incluye",
  "cuesta",
  "cobran",
  "pago",
  "costo",
  "renta",
];
